### ISSUE TITLE
什么时候支持多卡啊，另外有些参数default 和文档里说的不一致

### ISSUE THREAD

**Issue by lemon234071** [thu-coai/cotk#314]
比如seq2seq的wl，另外ubuntu的datapath好像没加//resouce：

**Comment by hzhwcmhf** [comment]
baseline的多卡可能暂时不会支持，现在没有时间弄这个。如果你有时间可以帮我们加一下
文档和默认参数的问题会修正，谢谢

**Comment by lemon234071** [comment]
谢谢奥，欸？我记得我把issue关了鸭

**Comment by hzhwcmhf** [comment]
我开的。把默认参数问题修正后会关闭这个issue

**Comment by lemon234071** [comment]
那我测的时候发现的小问题也留这里了呀？
metric里面的第一个example没有传dataloader到BleuCorpusMetric里面

**Comment by lemon234071** [comment]
在multi_turn_dialog.py中_load_data构建vocab那里，如果数据中含有self.ext_vocab中的特殊字符， 似乎会产生一些问题
