### ISSUE TITLE
检查version_up分支文档Quick Start和Practice: Implement a GRU Language Model部分

### ISSUE THREAD

**Issue by aaa123git** [thu-coai/cotk#403]
- version_up分支代码相对master进行了更新，有些API发生了变化，需要将文档中Quick Start和Practice: Implement a GRU Language Model部分的示例全部运行一遍，找出错误
- Quick Start的Publish Experiments / Reproduce Experiments 一节可以不管。
- 注意：要在开发者自己电脑上，用CoTK version_up分支的代码生成HTML文件，然后在本地浏览器打开。不要检查<https://thu-coai.github.io/cotk_docs/>，它是master分支的文档。

**Comment by hzhwcmhf** [comment]
Done
