### ISSUE TITLE
[Feature] 增加SentenceBERT

### ISSUE THREAD

**Issue by t1101675** [thu-coai/cotk#419]
**Describe the feature**
Step1: 增加Field里面SentenceBERT的支持
Step2: 增加SessionBERT、SentenceCandidateBERT

**Expected behavior**
Step1: LanguageGeneration\SingleTurnDialog\SentenceClassification可以指定pretrain=bert
Step2: MultiTurnDialog

**Additional context**
Add any other context about the feature here.
每一个step需要相应测试

**Comment by hzhwcmhf** [comment]
Done
