### ISSUE TITLE
[BUG] 修正version_up分支中cotk.dataloader使用url导入时错误

### ISSUE THREAD

**Issue by TissueC** [thu-coai/cotk#423]
**Describe the bug**
在导入数据集时使用url传参，会出现错误

> expected str, bytes or os.PathLike object, not NoneType

具体的，由例如 如下语句引发

```
import cotk.dataloader
dl_url = cotk.dataloader.MSCOCO("http://cotk-data.s3-ap-northeast-1.amazonaws.com/mscoco_small.zip#MSCOCO")
```

由未能在构造函数中正确传参导致，解决方法：修改cotk/file_utils/file_utils.py   188行
`resource_processor = ResourceProcessor.load_class(res_type + 'ResourceProcessor')()`
为
`resource_processor = ResourceProcessor.load_class(res_type + 'ResourceProcessor')(cache_dir=cache_dir)`

**Comment by hzhwcmhf** [comment]
需求：
* 删去ResourceProcessor的默认构造参数
* 增加对于url载入的test（这个部分我记得好像有，需要check一下功能是否正确运行）

**Comment by hzhwcmhf** [comment]
Done
