### ISSUE TITLE
[Models] CopyNet

### ISSUE THREAD

**Issue by hzhwcmhf** [thu-coai/cotk#8]
Refer to Incorporating Copying Mechanism in Sequence-to-Sequence Learning.

**Comment by hzhwcmhf** [comment]
Dataloader

* need new data? First try OpenSubtitles (give some statistic for copy)

Metric

* BLEU peplexity

**Comment by victorywys** [comment]
Plan to finish by 1.20.

**Comment by hzhwcmhf** [comment]
Pause due to #38

**Comment by hzhwcmhf** [comment]
Removed
